### ISSUE TITLE
hyperg is taking ~80% to ~99% CPU on Windows

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/simple-transfer#9]
when running from binaries on Windows 10, Task Manager reports excessive CPU usage from `hyperg`

![CPU Usage](https://user-images.githubusercontent.com/7963044/61064475-23431700-a402-11e9-877c-7e713871adb5.jpg)

![Clipboard - July 11, 2019 5_31 PM](https://user-images.githubusercontent.com/7963044/61064498-30f89c80-a402-11e9-96a7-e6479eb9515b.png)

**Comment by cryptobench** [comment]
1 more example of this issue on another windows instance over on the rocket chat

![image](https://user-images.githubusercontent.com/33448819/61093596-9755dd00-a44b-11e9-95a0-3f98723c268a.png)

**Comment by cryptobench** [comment]
One more. 

![image](https://user-images.githubusercontent.com/33448819/61094230-94102080-a44e-11e9-8e39-6d49003231ac.png)

**Comment by prekucki** [comment]
Build for fix tests:
[hyperg.zip](https://github.com/golemfactory/simple-transfer/files/3385083/hyperg.zip)

**Comment by tworec** [comment]
It does not eat whole CPU. Good to go

![image](https://user-images.githubusercontent.com/12720209/61119154-86808800-a49a-11e9-9e0b-67eb9ce4701e.png)

**Comment by weaselix** [comment]
Yes, I've checked it too - it fixes consumption of CPU. I've verified CPU consumption and correctness as well. (Correctness by manual running fixed hyperg and computing simple task - cube):
(provider was run with new (fixed) hyperg, requestor with an old hyperg)

**Comment by tworec** [comment]
user `bitlock` also reports it works smoothly
https://chat.golem.network/channel/testers?msg=7y3QBRRA8ssmTniyG

**Comment by ederenn** [comment]
New Hyperg seems to be working fine, checked requesting on: helicopter, classroom, blender boy, small shark
Node was providing as well.
When Golem is not computing CPU usage stays around 13% with all other system processes running

**Comment by ederenn** [comment]
https://github.com/golemfactory/golem/issues/4463 might be related
